/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CU-CP-Usage-Report-UeResourceReportItem.h"

asn_TYPE_member_t asn_MBR_CU_CP_Usage_Report_UeResourceReportItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CU_CP_Usage_Report_UeResourceReportItem, c_RNTI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_C_RNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"c-RNTI"
		},
	{ ATF_POINTER, 2, offsetof(struct CU_CP_Usage_Report_UeResourceReportItem, serving_Cell_RF_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serving-Cell-RF-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct CU_CP_Usage_Report_UeResourceReportItem, neighbor_Cell_RF),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"neighbor-Cell-RF"
		},
};
static const int asn_MAP_CU_CP_Usage_Report_UeResourceReportItem_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CU_CP_Usage_Report_UeResourceReportItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c-RNTI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* serving-Cell-RF-Type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* neighbor-Cell-RF */
};
asn_SEQUENCE_specifics_t asn_SPC_CU_CP_Usage_Report_UeResourceReportItem_specs_1 = {
	sizeof(struct CU_CP_Usage_Report_UeResourceReportItem),
	offsetof(struct CU_CP_Usage_Report_UeResourceReportItem, _asn_ctx),
	asn_MAP_CU_CP_Usage_Report_UeResourceReportItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_CU_CP_Usage_Report_UeResourceReportItem_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CU_CP_Usage_Report_UeResourceReportItem = {
	"CU-CP-Usage-Report-UeResourceReportItem",
	"CU-CP-Usage-Report-UeResourceReportItem",
	&asn_OP_SEQUENCE,
	asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1,
	sizeof(asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1)
		/sizeof(asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1[0]), /* 1 */
	asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1)
		/sizeof(asn_DEF_CU_CP_Usage_Report_UeResourceReportItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CU_CP_Usage_Report_UeResourceReportItem_1,
	3,	/* Elements count */
	&asn_SPC_CU_CP_Usage_Report_UeResourceReportItem_specs_1	/* Additional specs */
};

