/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#include "E2SM-KPM-IndicationMessage.h"

static asn_oer_constraints_t asn_OER_type_indicationMessage_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_indicationMessage_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_indicationMessage_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_KPM_IndicationMessage__indicationMessage, choice.indicationMessage_Format1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_KPM_IndicationMessage_Format1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indicationMessage-Format1"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_indicationMessage_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* indicationMessage-Format1 */
};
static asn_CHOICE_specifics_t asn_SPC_indicationMessage_specs_3 = {
	sizeof(struct E2SM_KPM_IndicationMessage__indicationMessage),
	offsetof(struct E2SM_KPM_IndicationMessage__indicationMessage, _asn_ctx),
	offsetof(struct E2SM_KPM_IndicationMessage__indicationMessage, present),
	sizeof(((struct E2SM_KPM_IndicationMessage__indicationMessage *)0)->present),
	asn_MAP_indicationMessage_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_indicationMessage_3 = {
	"indicationMessage",
	"indicationMessage",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_indicationMessage_constr_3, &asn_PER_type_indicationMessage_constr_3, CHOICE_constraint },
	asn_MBR_indicationMessage_3,
	1,	/* Elements count */
	&asn_SPC_indicationMessage_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_E2SM_KPM_IndicationMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_KPM_IndicationMessage, ric_Style_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-Style-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_KPM_IndicationMessage, indicationMessage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_indicationMessage_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indicationMessage"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_IndicationMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_KPM_IndicationMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-Style-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* indicationMessage */
};
static asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPM_IndicationMessage_specs_1 = {
	sizeof(struct E2SM_KPM_IndicationMessage),
	offsetof(struct E2SM_KPM_IndicationMessage, _asn_ctx),
	asn_MAP_E2SM_KPM_IndicationMessage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_IndicationMessage = {
	"E2SM-KPM-IndicationMessage",
	"E2SM-KPM-IndicationMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_KPM_IndicationMessage_tags_1,
	sizeof(asn_DEF_E2SM_KPM_IndicationMessage_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_IndicationMessage_tags_1[0]), /* 1 */
	asn_DEF_E2SM_KPM_IndicationMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_IndicationMessage_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_IndicationMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_KPM_IndicationMessage_1,
	2,	/* Elements count */
	&asn_SPC_E2SM_KPM_IndicationMessage_specs_1	/* Additional specs */
};

