/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_E2SM_KPM_IndicationHeader_Format1_H_
#define	_E2SM_KPM_IndicationHeader_Format1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include <NativeInteger.h>
#include "UE-Report-Type.h"
#include "GNB-DU-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GlobalKPMnode_ID;
struct NRCGI;
struct SNSSAI;
struct GNB_Name;
struct GlobalgNB_ID;

/* E2SM-KPM-IndicationHeader-Format1 */
typedef struct E2SM_KPM_IndicationHeader_Format1 {
	struct GlobalKPMnode_ID	*id_GlobalKPMnode_ID;	/* OPTIONAL */
	struct NRCGI	*nRCGI;	/* OPTIONAL */
	PLMN_Identity_t	*pLMN_Identity;	/* OPTIONAL */
	struct SNSSAI	*sliceID;	/* OPTIONAL */
	long	*fiveQI;	/* OPTIONAL */
	long	*qci;	/* OPTIONAL */
	UE_Report_Type_t	*message_Type;	/* OPTIONAL */
	GNB_DU_ID_t	*gNB_DU_ID;	/* OPTIONAL */
	struct GNB_Name	*gNB_Name;	/* OPTIONAL */
	struct GlobalgNB_ID	*global_GNB_ID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPM_IndicationHeader_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_IndicationHeader_Format1;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPM_IndicationHeader_Format1_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_KPM_IndicationHeader_Format1_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GlobalKPMnode-ID.h"
#include "NRCGI.h"
#include "SNSSAI.h"
#include "GNB-Name.h"
#include "GlobalgNB-ID.h"

#endif	/* _E2SM_KPM_IndicationHeader_Format1_H_ */
#include <asn_internal.h>
