#
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:18.04 AS oai-base
MAINTAINER Luis Ariza "lfarizav@idtolu.com"
ARG EURECOM_PROXY
ENV TZ=Europe
RUN apt-get update && apt-get install software-properties-common -y
RUN add-apt-repository -y ppa:myriadrf/drivers
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install sudo -y 
RUN apt-get install apt-utils -y 
RUN apt-get install vim-common -y
RUN apt-get install git -y
RUN rm -rf /var/lib/apt/lists/*

# In Eurecom env we need a git proxy
RUN /bin/bash -c "if [[ -v EURECOM_PROXY ]]; then git config --global http.proxy http://proxy.eurecom.fr:8080; fi"
RUN git clone https://gitlab.eurecom.fr/oai/openairinterface5g/ /openairinterface5g -b develop
RUN cd openairinterface5g && git branch
#RUN apt-get update && apt-get install software-properties-common -y
RUN add-apt-repository -y ppa:myriadrf/drivers && apt-get update && apt-get install -y limesuite \
liblimesuite-dev \
limesuite-udev \
limesuite-images
RUN apt-get install -y soapysdr-tools \
soapysdr-module-lms7

WORKDIR /openairinterface5g
COPY nasmesh.patch nasmesh.patch
RUN git apply nasmesh.patch
ENV USER=root
RUN apt-get update
RUN apt-get install sudo -y
RUN /bin/bash -c "source oaienv" && cd cmake_targets && ./build_oai -I -i -w LMSSDR #--build-lib enbscope
RUN git branch
WORKDIR /
COPY enb.band7.tm1.25PRB.lmssdr.conf /openairinterface5g/ci-scripts/conf_files/

ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown

LABEL org.label-schema.schema-version=1.0 \
      org.label-schema.name=oai-base \
      org.label-schema.version=$org_label_schema_version \
      org.label-schema.vcs-url=$org_label_schema_vcs_url \
      org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
      org.label-schema.build-date=$org_label_schema_build_date \
      org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date
