#
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


FROM centos:7.6.1810 AS oai-base
ARG EURECOM_PROXY
RUN yum update -y \
	&& yum install centos-release-scl -y \
	&& yum-config-manager --enable rhel-server-rhscl-7-rpms -y \
   	&& yum install -y \
	wget \
	vim-common \
	git \
	make \
	autoconf \
	automake \
	bc \
	bison \
	flex \
	libtool \
	patch \
	#sudo \
	openssl \
	gcc-c++ \
	devtoolset-7 \
        atlas-devel \
        blas \
        blas-devel \
        bzip2-devel \
        check \
        check-devel \
        elfutils-libelf-devel \
        gflags-devel \
        glog-devel \
        gmp-devel \
        gnutls-devel \
        guile-devel \
        kernel-devel \
        kernel-headers \
        lapack \
        lapack-devel \
        libasan \
        libconfig-devel \
        libevent-devel \
        libffi-devel \
        libgcrypt-devel \
        libidn-devel \
        libidn2-devel  \
        libtool \
        libusb-devel \
        libusbx-devel \
        libxml2-devel \
        libXpm-devel \
        libxslt-devel \
        libyaml-devel \
        lksctp-tools \
        lksctp-tools-devel \
        lz4-devel \
        mariadb-devel \
        nettle-devel \
        openssh-clients \
        openssh-server \
        openssl \
        openssl-devel \
        pkgconfig \
        psmisc \
        python3-pip.noarch \
	python-devel \
	python-mako \
        unzip \
        vim-common \
        xforms-devel \
        xz-devel \
        zlib-devel \
	scl-utils \
	bzip2 \
	#boost-devel \
    && yum clean all -y \
    && rm -rf /var/cache/yum \
    && pip3 install --user mako pexpect \ 
    && pip3 install six \
    && pip3 install requests


COPY scripts scripts/
RUN scl enable devtoolset-7 scripts/build_missing_packages 
RUN rm -rf /tmp/*

# In Eurecom env we need a git proxy
RUN /bin/bash -c "if [[ -v EURECOM_PROXY ]]; then git config --global http.proxy http://proxy.eurecom.fr:8080; fi"
RUN git clone https://gitlab.eurecom.fr/oai/openairinterface5g/ /openairinterface5g -b develop

WORKDIR /openairinterface5g
COPY nasmesh.patch nasmesh.patch
RUN git apply nasmesh.patch
#RUN /bin/bash -c "source oaienv" && cd cmake_targets && ./build_oai -I

ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown

LABEL org.label-schema.schema-version=1.0 \
      org.label-schema.name=oai-base \
      org.label-schema.version=$org_label_schema_version \
      org.label-schema.vcs-url=$org_label_schema_vcs_url \
      org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
      org.label-schema.build-date=$org_label_schema_build_date \
      org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date
