#
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG build_base

FROM $build_base AS enb-builder
WORKDIR /openairinterface5g
ENV USER=root
RUN ln -sf /usr/local/bin/cmake /usr/local/bin/cmake3

RUN cd /openairinterface5g/cmake_targets \
    && ln -sf /usr/local/bin/asn1c_oai /usr/local/bin/asn1c \
    && ln -sf /usr/local/share/asn1c_oai /usr/local/share/asn1c \
    && ./build_oai -c --eNB -w USRP --verbose-compile

FROM centos:7.6.1810 AS lte-softmodem
RUN yum update -y && yum install -y nettle.x86_64 \
 	        lksctp-tools.x86_64 \
		 libyaml.x86_64 \
		 iperf3.x86_64 \
		 blas.x86_64 \
		 atlas.x86_64 \
		 atlas-devel.x86_64 \
		 libconfig-devel.x86_64 \
		 iptables.x86_64 \
		 lapack-devel.x86_64 \
		 && yum clean all -y \
    		 && rm -rf /var/cache/yum 

WORKDIR /openairinterface5g/ci-scripts
COPY --from=enb-builder /openairinterface5g/ci-scripts/ .
WORKDIR /openairinterface5g/cmake_targets
COPY --from=enb-builder /openairinterface5g/cmake_targets/ .

COPY --from=enb-builder /usr/local/bin/uhd_* /usr/local/bin/
COPY --from=enb-builder /usr/local/share/uhd/ /usr/local/share/uhd/
COPY --from=enb-builder /usr/local/lib64/libuhd* /usr/local/lib64/
COPY --from=enb-builder /usr/lib64/libboost_* /usr/lib64/
COPY --from=enb-builder /usr/lib64/libusb* /usr/lib64/
COPY --from=enb-builder /usr/lib/libboost_* /usr/lib/
COPY --from=enb-builder /usr/local/lib/libproto* /usr/local/lib/


RUN find . -name "*.h" -type f -delete
RUN find . -name "*.c" -type f -delete
RUN find / -name "*.a" -type f -delete
RUN find / -name "*.tar.gz" -type f -delete
RUN rm -rf ./ran_build/build/CMakeFiles/

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64/:/usr/local/lib:/usr/lib

# S1U, GTP/UDP
EXPOSE 2152/udp  
# ?
EXPOSE 22100/tcp 
# S1C, SCTP/UDP
EXPOSE 36412/udp 
# X2C, SCTP/UDP
EXPOSE 36422/udp 
# M2C, SCTP/UDP
EXPOSE 36443/udp 
# M3C, SCTP/UDP
EXPOSE 36444/udp 
# IF5 / ORI (control)
EXPOSE 50000/udp 
# IF5 / ECPRI (data)
EXPOSE 50001/udp 



# Label image
ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown

LABEL org.label-schema.schema-version=1.0 \
      org.label-schema.name=lte-softmodem \
      org.label-schema.version=$org_label_schema_version \
      org.label-schema.vcs-url=$org_label_schema_vcs_url \
      org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
      org.label-schema.build-date=$org_label_schema_build_date \
      org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date
