#
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG build_base

FROM $build_base AS ue-builder
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    linux-headers-`uname -r` \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /openairinterface5g
ENV USER=root
RUN /bin/bash -c "source oaienv" && cd cmake_targets && ./build_oai --UE -w USRP

FROM ubuntu:18.04 AS lte-uesoftmodem
RUN apt-get update && apt-get install -y \
    libssl1.0.0 \
    libnettle6 \
    libsctp1 \
    libforms2 \
    libconfig9 \
    libblas3 \
    liblapacke \
    sudo \
    dnsutils \
    iproute2 \
    iputils-ping \
    net-tools \
    libblas3 \
    libatlas-base-dev \ 
    libblas-dev \
    iperf \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /openairinterface5g/cmake_targets
COPY --from=ue-builder /openairinterface5g/cmake_targets .
COPY --from=ue-builder /openairinterface5g/targets/bin/nvram .
COPY --from=ue-builder /openairinterface5g/targets/bin/usim .
COPY --from=ue-builder /openairinterface5g/targets ../targets

# Label image
ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown

LABEL org.label-schema.schema-version=1.0 \
      org.label-schema.name=lte-uesoftmodem \
      org.label-schema.version=$org_label_schema_version \
      org.label-schema.vcs-url=$org_label_schema_vcs_url \
      org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
      org.label-schema.build-date=$org_label_schema_build_date \
      org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date
