#
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##FROM ubuntu:16.04 AS oai-base
##RUN apt-get update && apt-get install -y \
##    sudo \
##    vim-common \
##    git \
##    build-essential \
##    cmake \
## && rm -rf /var/lib/apt/lists/*
#

FROM centos:7.6.1810 AS oai-base
RUN yum update -y && yum install -y \
vim-common 	\
git \
make \
cmake3 \
autoconf \
automake \
bc \
bison \
flex \
libtool \
patch \
devtoolset-7 \
sudo \
openssl \
gcc-c++ 


#ENV GIT_SSL_NO_VERIFY=true
ENV USER=root

# In Eurecom env we need a git proxy
RUN if [[ -v EURECOM_PROXY ]]; then git config --global http.proxy http://proxy.eurecom.fr:8080; fi
RUN GIT_SSL_NO_VERIFY=true git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git /openairinterface5g -b develop

WORKDIR /openairinterface5g
COPY nasmesh.patch nasmesh.patch
RUN git apply nasmesh.patch
RUN /bin/bash -c "source oaienv" && cd cmake_targets && ./build_oai -I


COPY scripts scripts/
RUN scl enable devtoolset-7 scripts/build_missing_packages

ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown

LABEL org.label-schema.schema-version=1.0 \
      org.label-schema.name=oai-base \
      org.label-schema.version=$org_label_schema_version \
      org.label-schema.vcs-url=$org_label_schema_vcs_url \
      org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
      org.label-schema.build-date=$org_label_schema_build_date \
      org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date
