/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CU-CP-Usage-Report-Per-UE.h"

static int
memb_cellResourceReportList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 16384)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_cellResourceReportList_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..16384)) */};
static asn_per_constraints_t asn_PER_type_cellResourceReportList_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_cellResourceReportList_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..16384)) */};
static asn_per_constraints_t asn_PER_memb_cellResourceReportList_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_cellResourceReportList_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CU_CP_Usage_Report_CellResourceReportItem,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_cellResourceReportList_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_cellResourceReportList_specs_2 = {
	sizeof(struct CU_CP_Usage_Report_Per_UE__cellResourceReportList),
	offsetof(struct CU_CP_Usage_Report_Per_UE__cellResourceReportList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cellResourceReportList_2 = {
	"cellResourceReportList",
	"cellResourceReportList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_cellResourceReportList_tags_2,
	sizeof(asn_DEF_cellResourceReportList_tags_2)
		/sizeof(asn_DEF_cellResourceReportList_tags_2[0]) - 1, /* 1 */
	asn_DEF_cellResourceReportList_tags_2,	/* Same as above */
	sizeof(asn_DEF_cellResourceReportList_tags_2)
		/sizeof(asn_DEF_cellResourceReportList_tags_2[0]), /* 2 */
	{ &asn_OER_type_cellResourceReportList_constr_2, &asn_PER_type_cellResourceReportList_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_cellResourceReportList_2,
	1,	/* Single element */
	&asn_SPC_cellResourceReportList_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CU_CP_Usage_Report_Per_UE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CU_CP_Usage_Report_Per_UE, cellResourceReportList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_cellResourceReportList_2,
		0,
		{ &asn_OER_memb_cellResourceReportList_constr_2, &asn_PER_memb_cellResourceReportList_constr_2,  memb_cellResourceReportList_constraint_1 },
		0, 0, /* No default value */
		"cellResourceReportList"
		},
};
static const ber_tlv_tag_t asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CU_CP_Usage_Report_Per_UE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* cellResourceReportList */
};
asn_SEQUENCE_specifics_t asn_SPC_CU_CP_Usage_Report_Per_UE_specs_1 = {
	sizeof(struct CU_CP_Usage_Report_Per_UE),
	offsetof(struct CU_CP_Usage_Report_Per_UE, _asn_ctx),
	asn_MAP_CU_CP_Usage_Report_Per_UE_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CU_CP_Usage_Report_Per_UE = {
	"CU-CP-Usage-Report-Per-UE",
	"CU-CP-Usage-Report-Per-UE",
	&asn_OP_SEQUENCE,
	asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1,
	sizeof(asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1)
		/sizeof(asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1[0]), /* 1 */
	asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1,	/* Same as above */
	sizeof(asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1)
		/sizeof(asn_DEF_CU_CP_Usage_Report_Per_UE_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CU_CP_Usage_Report_Per_UE_1,
	1,	/* Elements count */
	&asn_SPC_CU_CP_Usage_Report_Per_UE_specs_1	/* Additional specs */
};

