/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_E2SM_KPM_IndicationMessage_H_
#define	_E2SM_KPM_IndicationMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RIC-Style-Type.h"
#include "E2SM-KPM-IndicationMessage-Format1.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_KPM_IndicationMessage__indicationMessage_PR {
	E2SM_KPM_IndicationMessage__indicationMessage_PR_NOTHING,	/* No components present */
	E2SM_KPM_IndicationMessage__indicationMessage_PR_indicationMessage_Format1
	/* Extensions may appear below */
	
} E2SM_KPM_IndicationMessage__indicationMessage_PR;

/* E2SM-KPM-IndicationMessage */
typedef struct E2SM_KPM_IndicationMessage {
	RIC_Style_Type_t	 ric_Style_Type;
	struct E2SM_KPM_IndicationMessage__indicationMessage {
		E2SM_KPM_IndicationMessage__indicationMessage_PR present;
		union E2SM_KPM_IndicationMessage__indicationMessage_u {
			E2SM_KPM_IndicationMessage_Format1_t	 indicationMessage_Format1;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} indicationMessage;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPM_IndicationMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_IndicationMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPM_IndicationMessage_H_ */
#include <asn_internal.h>
