/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GNB_Name_H_
#define	_GNB_Name_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GNB-DU-Name.h"
#include "GNB-CU-CP-Name.h"
#include "GNB-CU-UP-Name.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GNB_Name_PR {
	GNB_Name_PR_NOTHING,	/* No components present */
	GNB_Name_PR_gNB_DU_Name,
	GNB_Name_PR_gNB_CU_CP_Name,
	GNB_Name_PR_gNB_CU_UP_Name
	/* Extensions may appear below */
	
} GNB_Name_PR;

/* GNB-Name */
typedef struct GNB_Name {
	GNB_Name_PR present;
	union GNB_Name_u {
		GNB_DU_Name_t	 gNB_DU_Name;
		GNB_CU_CP_Name_t	 gNB_CU_CP_Name;
		GNB_CU_UP_Name_t	 gNB_CU_UP_Name;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_Name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNB_Name;
extern asn_CHOICE_specifics_t asn_SPC_GNB_Name_specs_1;
extern asn_TYPE_member_t asn_MBR_GNB_Name_1[3];
extern asn_per_constraints_t asn_PER_type_GNB_Name_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _GNB_Name_H_ */
#include <asn_internal.h>
