/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PF_Container_H_
#define	_PF_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ODU-PF-Container.h"
#include "OCUCP-PF-Container.h"
#include "OCUUP-PF-Container.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PF_Container_PR {
	PF_Container_PR_NOTHING,	/* No components present */
	PF_Container_PR_oDU,
	PF_Container_PR_oCU_CP,
	PF_Container_PR_oCU_UP
	/* Extensions may appear below */
	
} PF_Container_PR;

/* PF-Container */
typedef struct PF_Container {
	PF_Container_PR present;
	union PF_Container_u {
		ODU_PF_Container_t	 oDU;
		OCUCP_PF_Container_t	 oCU_CP;
		OCUUP_PF_Container_t	 oCU_UP;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PF_Container_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PF_Container;
extern asn_CHOICE_specifics_t asn_SPC_PF_Container_specs_1;
extern asn_TYPE_member_t asn_MBR_PF_Container_1[3];
extern asn_per_constraints_t asn_PER_type_PF_Container_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PF_Container_H_ */
#include <asn_internal.h>
