/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/home/rshacham/e2sm-kpm-v01.02.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Timestamp_H_
#define	_Timestamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Timestamp */
typedef OCTET_STRING_t	 Timestamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Timestamp;
asn_struct_free_f Timestamp_free;
asn_struct_print_f Timestamp_print;
asn_constr_check_f Timestamp_constraint;
ber_type_decoder_f Timestamp_decode_ber;
der_type_encoder_f Timestamp_encode_der;
xer_type_decoder_f Timestamp_decode_xer;
xer_type_encoder_f Timestamp_encode_xer;
oer_type_decoder_f Timestamp_decode_oer;
oer_type_encoder_f Timestamp_encode_oer;
per_type_decoder_f Timestamp_decode_uper;
per_type_encoder_f Timestamp_encode_uper;
per_type_decoder_f Timestamp_decode_aper;
per_type_encoder_f Timestamp_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Timestamp_H_ */
#include <asn_internal.h>
